# Generated by Django 4.0.4 on 2022-04-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=8)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=50)),
                ('email', models.TextField()),
                ('specialty', models.CharField(max_length=100)),
                ('officelocation', models.TextField(max_length=50)),
                ('sector', models.TextField()),
            ],
        ),
    ]
